services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - "8081:80"    # Changed from 8080 to 8081 to avoid conflict
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"    # Keep phpMyAdmin on port 8080
    environment:
      - PMA_HOST=db  # Ensure this is correct

  composer:
    image: composer:2.5.3
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: ["composer", "install"]
